version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    environment:
      CI: 1
    steps:
      - checkout
      - restore_cache:
          key: bilt-{{ .Branch }}
      - run:
          name: Setup nvm and npm and git
          command: |
            set +e
            touch $BASH_ENV
            export NODE_VERSION=10.6.0
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
            git config --global user.email "gil@tayar.org"
            git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
            git status

      - run:
          name: Install correct Node version
          command: |
            nvm install 10.6.0
            nvm alias default 10.6.0
      - run:
          name: Install bilt
          command: |
              npm install -g @bilt/bilt-cli
      - run:
          name: Bild
          command: bilt -u @bilt/bilt-cli --no-rebuild

      - save_cache:
          key: bilt-{{ .Branch }}
          paths:
            - ".bilt"
